### ISSUE TITLE
Plugin settings - login not working

### ISSUE THREAD

**Issue by Macaper** [davekelly/aaOnepageCrm#2]
Installed the plugin on WP 3.5
When I try to add my username and password in the plugin settings I get incorrect username or password as answer, but they are 100% correct.

**Comment by davekelly** [comment]
Thanks for letting me know. 

I've updated the plugin and you shouldn't run into that login problem again. You should download and install a fresh copy on your site.

**Comment by Macaper** [comment]
New error after login OK on settings

WP_Error Object ( [errors] => Array ( [http_request_failed] => Array ( [0] => connect() timed out! ) ) [error_data] => Array ( ) )

Sorry to be a bother...

Hmm, maby delete this, cause it looks like entire onepage is down app.onepagecrm.com is not responding.
