### ISSUE TITLE
Stored XSS Bug

### ISSUE THREAD

**Issue by Yogendra0Sharma** [davekelly/aaOnepageCrm#3]
Hello,
I found Stored Xss Bug.
Reproduction Steps.
1. Go to OnepageCrm Plugin Login.
2.Enter Username & Password as Xss Payload @ http://pastebin.com/iyp2Cye2
3.Hit Enter.
4.Payload Executed & Stored.

Their is No User input Filter..
![wp xss](https://cloud.githubusercontent.com/assets/1375860/3063976/81cec7a8-e24a-11e3-851e-83c45938ed8f.png)

**Comment by davekelly** [comment]
Thanks. I've updated the login form to escape output
