### ISSUE TITLE
Tags not populating in drop down

### ISSUE THREAD

**Issue by tjtherese** [davekelly/aaOnepageCrm#4]
I just installed the plug-in-- but the tags that I have set up in OnePageCRM are not populating to the tags option in the plugin.  I tried deactivating, logging out and logging back in and reactivating--still, nothing populates under that drop down.  THANKS.

**Comment by davekelly** [comment]
Thanks for letting me know @tjtherese 

There seems to have been a change in the way tags were displayed - I've made a change to fix it. If you download the updated version it should work now.

Dave.

**Comment by tjtherese** [comment]
Thank you Dave…

Would you be so kind as to send me the link again to the download page?  For some reason, I’m not finding the link here in my bookmarks.

Theresa French

Transformational Speaker & Self-Mastery Coach

Office (612) 356-2606  |   Cell (507) 271-5605

 http://www.theresatalks.com/ www.TheresaTalks.com

**Comment by davekelly** [comment]
Sure, it's https://github.com/davekelly/aaOnepageCrm/archive/master.zip
